config:
  mailerMode: smtp
  testMailerEnabled: false
  smtpHost: sandbox.smtp.mailtrap.io
  smtpPort: 2525
  smtpFrom: identity-staging@example.test
  publicAppURL: https://staging.example.test
secret:
  smtpUsername: ""
  smtpPassword: ""
