{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "gateway.fullname" . }}
spec:
  podSelector:
    matchLabels:
{{ include "gateway.labels" . | indent 6 }}
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
{{ toYaml .Values.networkPolicy.gatewayNamespaceLabels | indent 14 }}
          podSelector:
            matchLabels:
{{ toYaml .Values.networkPolicy.gatewayPodLabels | indent 14 }}
      ports: [{ protocol: TCP, port: 8080 }]
    - from:
        - namespaceSelector:
            matchLabels:
{{ toYaml .Values.networkPolicy.ingressNamespaceLabels | indent 14 }}
          podSelector:
            matchLabels:
{{ toYaml .Values.networkPolicy.ingressPodLabels | indent 14 }}
      ports: [{ protocol: TCP, port: {{ .Values.networkPolicy.ingressPort }} }]
    - from:
        - namespaceSelector:
            matchLabels:
{{ toYaml .Values.networkPolicy.monitoringNamespaceLabels | indent 14 }}
          podSelector:
            matchLabels:
{{ toYaml .Values.networkPolicy.monitoringPodLabels | indent 14 }}
      ports: [{ protocol: TCP, port: 8080 }]
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
{{ toYaml .Values.networkPolicy.dnsNamespaceLabels | indent 14 }}
          podSelector:
            matchLabels:
{{ toYaml .Values.networkPolicy.dnsPodLabels | indent 14 }}
      ports: [{ protocol: UDP, port: 53 }, { protocol: TCP, port: 53 }]
    - to:
        - namespaceSelector:
            matchLabels:
{{ toYaml .Values.networkPolicy.identityNamespaceLabels | indent 14 }}
          podSelector:
            matchLabels:
{{ toYaml .Values.networkPolicy.identityPodLabels | indent 14 }}
      ports: [{ protocol: TCP, port: {{ .Values.networkPolicy.identityPort }} }]
    - to:
        - namespaceSelector:
            matchLabels:
{{ toYaml .Values.networkPolicy.ordersNamespaceLabels | indent 14 }}
          podSelector:
            matchLabels:
{{ toYaml .Values.networkPolicy.ordersPodLabels | indent 14 }}
      ports: [{ protocol: TCP, port: {{ .Values.networkPolicy.ordersPort }} }]
    - to:
        - namespaceSelector:
            matchLabels:
{{ toYaml .Values.networkPolicy.redisNamespaceLabels | indent 14 }}
          podSelector:
            matchLabels:
{{ toYaml .Values.networkPolicy.redisPodLabels | indent 14 }}
      ports: [{ protocol: TCP, port: 6379 }]
    - to:
        - namespaceSelector:
            matchLabels:
{{ toYaml .Values.networkPolicy.otelNamespaceLabels | indent 14 }}
          podSelector:
            matchLabels:
{{ toYaml .Values.networkPolicy.otelPodLabels | indent 14 }}
      ports: [{ protocol: TCP, port: 4317 }]
{{- end }}
