apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "identity.fullname" . }}-config
data:
  IDENTITY_ISSUER: {{ .Values.config.issuer | quote }}
  IDENTITY_HUMAN_AUDIENCE: {{ .Values.config.humanAudience | quote }}
  IDENTITY_MACHINE_AUDIENCE: {{ .Values.config.machineAudience | quote }}
  IDENTITY_LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  IDENTITY_DEMO_REGISTRATION_ENABLED: {{ .Values.config.demoRegistration | quote }}
  IDENTITY_KAFKA_BROKERS: {{ .Values.config.kafkaBrokers | quote }}
  IDENTITY_SIGNING_KEY_PATH: {{ .Values.config.signingKeyPath | quote }}
  IDENTITY_SIGNING_KEY_ID: {{ .Values.config.signingKeyID | quote }}
  IDENTITY_MAILER_MODE: {{ .Values.config.mailerMode | quote }}
  IDENTITY_TEST_MAILER_ENABLED: {{ .Values.config.testMailerEnabled | quote }}
  IDENTITY_SMTP_HOST: {{ .Values.config.smtpHost | quote }}
  IDENTITY_SMTP_PORT: {{ .Values.config.smtpPort | quote }}
  IDENTITY_SMTP_FROM: {{ .Values.config.smtpFrom | quote }}
  IDENTITY_PUBLIC_APP_URL: {{ .Values.config.publicAppURL | quote }}
