apiVersion: v1
kind: Secret
metadata:
  name: {{ include "identity.fullname" . }}-secret
type: Opaque
stringData:
  IDENTITY_DATABASE_URL: {{ .Values.secret.databaseURL | default .Values.config.databaseURL | quote }}
  IDENTITY_REDIS_URL: {{ .Values.secret.redisURL | default .Values.config.redisURL | quote }}
  signing-key.pem: {{ .Values.secret.signingKeyPEM | quote }}
